/**
 * Creates the deterministic demo fixture repo at .demo/todo-app (separate from any
 * real project). Re-run with --force to recreate it from scratch.
 *   npm run demo:setup [-- --force]
 */
import { existsSync } from "node:fs";
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { git } from "../server/git.ts";

const ROOT = path.resolve(".demo", "todo-app");
const MARKER = ".colab-fixture";

const README = [
  "# Todo",
  "",
  "A tiny in-memory todo service used to demo collaborative agent supervision.",
  "",
  "## Usage",
  "",
  "```js",
  'import { createStore } from "./src/store.js";',
  "const store = createStore();",
  'store.add("Write the demo script");',
  "store.complete(1);",
  "console.log(store.list());",
  "```",
  "",
  "## Design notes",
  "",
  "- Todos live in memory; restarting the process loses them.",
  "- IDs are sequential integers starting at 1.",
  "- Completing an unknown id throws an error.",
  "- The store has no external dependencies.",
  "",
  "## Development",
  "",
  "Run the tests with `npm test`. They use the built-in Node test runner.",
  "",
  "## Roadmap",
  "",
  "- Persist todos (database not chosen yet).",
  "- Add due dates.",
  "- Add priorities.",
  "",
].join("\n");

const FILES: Record<string, string> = {
  "README.md": README,
  "package.json": JSON.stringify({ name: "todo-app", version: "0.1.0", private: true, type: "module", scripts: { test: "node --test" } }, null, 2) + "\n",
  "src/config.js": ['// Product configuration.', 'export const APP_NAME = "Todo";', "export const MAX_TODOS = 500;", ""].join("\n"),
  "src/store.js": [
    'import { MAX_TODOS } from "./config.js";',
    "",
    "export function createStore() {",
    "  const todos = [];",
    "  let nextId = 1;",
    "  return {",
    "    add(title) {",
    '      if (todos.length >= MAX_TODOS) throw new Error("too many todos");',
    "      const todo = { id: nextId++, title, done: false };",
    "      todos.push(todo);",
    "      return todo;",
    "    },",
    "    complete(id) {",
    "      const t = todos.find((x) => x.id === id);",
    "      if (!t) throw new Error(`unknown todo ${id}`);",
    "      t.done = true;",
    "      return t;",
    "    },",
    "    list() {",
    "      return todos.map((t) => ({ ...t }));",
    "    },",
    "  };",
    "}",
    "",
  ].join("\n"),
  "test/store.test.js": [
    'import { test } from "node:test";',
    'import assert from "node:assert/strict";',
    'import { createStore } from "../src/store.js";',
    "",
    'test("adds and completes todos", () => {',
    "  const s = createStore();",
    '  s.add("a");',
    "  s.complete(1);",
    '  assert.deepEqual(s.list(), [{ id: 1, title: "a", done: true }]);',
    "});",
    "",
    'test("rejects unknown ids", () => {',
    "  assert.throws(() => createStore().complete(9));",
    "});",
    "",
  ].join("\n"),
  // Used by the MOCK demo scripts so the rename is deterministic.
  "scripts/rename.mjs": [
    'import { readFileSync, writeFileSync } from "node:fs";',
    "const [name, flag] = process.argv.slice(2);",
    'if (!name) throw new Error("usage: node scripts/rename.mjs <name> [--config-only]");',
    'const cfg = readFileSync("src/config.js", "utf8").replace(/APP_NAME = ".*?"/, `APP_NAME = "${name}"`);',
    'writeFileSync("src/config.js", cfg);',
    'if (flag !== "--config-only") {',
    '  const lines = readFileSync("README.md", "utf8").split("\\n");',
    "  lines[0] = `# ${name}`;",
    '  writeFileSync("README.md", lines.join("\\n"));',
    "}",
    'console.log(`renamed to ${name}`);',
    "",
  ].join("\n"),
  [MARKER]: "This repository was generated by `npm run demo:setup`. Safe to delete.\n",
};

/** Writes the fixture files into an empty directory and commits them on main. */
export async function createFixture(root: string) {
  for (const [p, c] of Object.entries(FILES)) {
    const f = path.join(root, p);
    await mkdir(path.dirname(f), { recursive: true });
    await writeFile(f, c);
  }
  await git(["init", "-q", "-b", "main"], { cwd: root });
  await git(["add", "-A"], { cwd: root });
  await git(["-c", "user.name=Demo", "-c", "user.email=demo@localhost", "commit", "-q", "-m", "Initial todo app"], { cwd: root });
}

async function main() {
  const force = process.argv.includes("--force");
  if (existsSync(ROOT)) {
    if (!force) {
      console.log(`Demo repo already exists at ${ROOT}. Use --force to recreate it.`);
      return;
    }
    if (!existsSync(path.join(ROOT, MARKER))) throw new Error(`${ROOT} exists but is not a generated fixture; refusing to delete it.`);
    await git(["worktree", "prune"], { cwd: ROOT }).catch(() => {});
    await rm(ROOT, { recursive: true, force: true, maxRetries: 3 });
  }
  await createFixture(ROOT);
  console.log(`Demo repo ready at ${ROOT}\nStart the room with: npm run demo`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) main().catch((e) => {
  console.error(e.message);
  process.exit(1);
});
